### ISSUE TITLE
Errors when using cals.sch from nvdl in Oxygen

### ISSUE THREAD

**Issue by dwcramer** [nigelwhitaker/cals-table-schematron#1]
Hi there,

We've had some trouble with DeltaXML+FOP when we feed it tables with questionable markup, so this looks like just the thing to help us out. 

Update:  When I follow the instructions in https://github.com/nigelwhitaker/cals-table-schematron/blob/master/doc/UsingInOxygen.txt, validation works. I guess Jing isn't using the same version of Schematron?

Using XML Editor 19.0, build 2017042020, I've dropped a reference to cals.sch in our .nvdl file. It was complaining about the namespace `xs` not being declared, but I got that to go away by adding `<ns prefix="xs" uri="http://www.w3.org/2001/XMLSchema"/>` to cals.sch (see https://github.com/nigelwhitaker/cals-table-schematron/pull/2). However, I'm still getting the following errors:

```
System ID: /Users/dcramer/dcramer_anatine/dcramer_anatine/depot/www/hwtechdocs/doctools/third-party-tools/cals-table-schematron/source/cals.sch
Main validation file: /Users/dcramer/dcramer_anatine/dcramer_anatine/depot/www/hwtechdocs/docshared/testing/test-misc-formatting.xml
Scenario name: DocBook 5 - Extension
Schema: /Users/dcramer/dcramer_anatine/dcramer_anatine/depot/www/hwtechdocs/doctools/rng/multischema-config.nvdl
Document type: DocBook 5 - Extension
Engine name: Jing
Severity: fatal
Description: Variable occupied has not been declared (or its declaration is not in scope)

System ID: /Users/dcramer/dcramer_anatine/dcramer_anatine/depot/www/hwtechdocs/doctools/third-party-tools/cals-table-schematron/source/cals.sch
Main validation file: /Users/dcramer/dcramer_anatine/dcramer_anatine/depot/www/hwtechdocs/docshared/testing/test-misc-formatting.xml
Scenario name: DocBook 5 - Extension
Schema: /Users/dcramer/dcramer_anatine/dcramer_anatine/depot/www/hwtechdocs/doctools/rng/multischema-config.nvdl
Document type: DocBook 5 - Extension
Engine name: Jing
Severity: fatal
Description: Variable occupied has not been declared (or its declaration is not in scope)

System ID: /Users/dcramer/dcramer_anatine/dcramer_anatine/depot/www/hwtechdocs/doctools/rng/multischema-config.nvdl
Main validation file: /Users/dcramer/dcramer_anatine/dcramer_anatine/depot/www/hwtechdocs/docshared/testing/test-misc-formatting.xml
Scenario name: DocBook 5 - Extension
Schema: /Users/dcramer/dcramer_anatine/dcramer_anatine/depot/www/hwtechdocs/doctools/rng/multischema-config.nvdl
Document type: DocBook 5 - Extension
Engine name: Jing
Severity: error
Description: java.lang.IllegalStateException-Errors were reported during stylesheet compilation

System ID: /Users/dcramer/dcramer_anatine/dcramer_anatine/depot/www/hwtechdocs/docshared/testing/test-misc-formatting.xml
Main validation file: /Users/dcramer/dcramer_anatine/dcramer_anatine/depot/www/hwtechdocs/docshared/testing/test-misc-formatting.xml
Scenario name: DocBook 5 - Extension
Schema: /Users/dcramer/dcramer_anatine/dcramer_anatine/depot/www/hwtechdocs/doctools/rng/multischema-config.nvdl
Document type: DocBook 5 - Extension
Engine name: Jing
Severity: error
Description: IllegalStateException - cannot validate without schema
```

**Comment by nigelwhitaker** [comment]
Hi David,  I have tended to use the 'skeleton' implementation of schematron rather than Jing/nvdl.

The skeleton has a new home at:  https://github.com/Schematron/schematron and I believe this is the basis of the version in oxygen.

In our DeltaXML products we are using some customisations of the base code and we've created a fork:  
https://github.com/DeltaXML/schematron
The issue-20a-xslt3 branch is our simple customization for XSLT3 support and an outstanding issue that I was preparing to do a pull-reqeust on.

I'm also hoping to address https://github.com/Schematron/schematron/issues/21 and get some robust code into a pull-request for that too (our current implementation is based on post-processing the generated XSLT).

Our use of the skeleton was based on a need to have something that could run inside our comparison pipelines in our products and the generated XSLT fits well here.  However, the utility as standalone  schematron so that it can be used for checking in editing tools (eg oxygen)  is also important and I'll try to take a look at jing/nvdl soon.

Many thanks for the first feedback on the schematron (hopefully sorted out a watch for future notifications).  Nigel

**Comment by nigelwhitaker** [comment]
I didn't know that the Jing implementation was based on XSLT until I found:  http://www.mail-archive.com/oxygen-user@oxygenxml.com/msg03099.html

**Comment by dwcramer** [comment]
It ended up being a good thing not having this schematron inside our main nvdl validation. The problem is that for large documents with lots of tables, the table validation is expensive enough to slow things down substantially. As a result, I've made a separate "Extended CALS table validation" validation scenario that is off by default. Our users can run it periodically to catch problems. I'll probably also add it to our build pipeline, but maybe have that run only for release candidate builds or something.
